name: CD – Deploy to Azure

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform – Provision Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infra Code
        uses: actions/checkout@v4
        with:
          path: infra

      - name: Azure Login for Terraform
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  deploy:
    name: Deploy App Container
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login for Deployment
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure Web App Container
        run: |
          az webapp config container set \
            --resource-group suml-rg \
            --name suml-webapp \
            --docker-custom-image-name ${{ secrets.DOCKERHUB_USERNAME }}/asystent-snu:latest