name: Build & Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write       # jeśli używasz GitHub Container Registry
      id-token: write       # opcjonalnie do Azure/AWS loginów OIDC

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch support, opcjonalnie)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        # Dla Docker Hub:
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Jeśli używasz GitHub Container Registry, zamiast tego:
        # with:
        #   registry: ghcr.io
        #   username: ${{ github.actor }}
        #   password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            your-dockerhub-username/asystent-snu:latest
            your-dockerhub-username/asystent-snu:${{ github.sha }}

      - name: Image digest
        run: echo "Image digest: ${{ steps.build-and-push.outputs.digest }}"
